script: 'bundle exec rake -t test'
language: ruby
sudo: false

rvm:
  - 2.0.0
  - 2.1
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-9.0.0.0
  - rbx
matrix:
  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/rails_41.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_42.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_50.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - rvm: jruby-9.0.0.0
    - rvm: rbx
gemfile:
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_edge.gemfile
