script: "bundle exec rake spec"
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx-19mode
gemfile:
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
